Add asset
ARCADE-TEK-2026/archi_arcade pull request #113
Opened 2023-04-02 20:03 UTC by alexandrelagasse

Asset

2023-04-02 20:27 UTC, Saverio976 requested changes

2023-04-02 20:27 UTC, Saverio976 commented on asset/normal/body.png
ça serait possible d'avoir juste un carré bleu qui couvre toute la surface (pour les personnes qui ont pas envie de faire d'annimation pour le snake

2023-04-03 14:05 UTC, guillaumeAbel commented
Comme c'est les path du snake et que y'aura d'autre jeux c'est mieux de tout mettre dans un dossier snake/ et le dossiers assets/ t'a oublié le s

2023-04-03 15:55 UTC, Saverio976 approved these changes

2023-04-03 15:56 UTC, merged